// Plain-English "cheat sheet" shown inside each playbook (Content Studio → Playbooks).
// One entry per skill slug so a non-marketer knows: what it is, when to use it, what to
// type, what they'll get, and how to tell if the result is good. GooCampus-flavoured
// (Indian medical students/doctors — NEET, MBBS/PG abroad, licensing).

export type PlaybookGuide = {
  tagline: string;  // what it is, in one plain sentence
  useWhen: string;  // when to reach for it
  example: string;  // a ready-to-run task the user can drop into the box
  expect: string;   // what the result will look like
  verify: string;   // how to tell it's good / correct
};

export const PLAYBOOK_GUIDES: Record<string, PlaybookGuide> = {
  "cold-email": {
    tagline: "Writes cold outreach emails (and follow-ups) that actually get replies.",
    useWhen: "You want to email schools, hospitals, coaches, or partners who don't know GooCampus yet.",
    example: "Write a cold email to MBBS-abroad consultants proposing a referral partnership with GooCampus, plus 2 follow-ups.",
    expect: "A short subject line, a 4–6 line email, and 2 follow-up messages spaced over a week.",
    verify: "Would you reply to it? It should be about them, not us, with one clear ask — no jargon, no wall of text.",
  },
  "copy-editing": {
    tagline: "Improves copy you already have — tighter, clearer, on-brand.",
    useWhen: "You have website text, a caption, or a brochure that feels off and want it sharpened.",
    example: "Improve this GooCampus homepage intro: [paste your current text].",
    expect: "A cleaner rewrite plus a note on what was changed and why.",
    verify: "The meaning is unchanged but it reads simpler and stronger; no invented claims added.",
  },
  "copywriting": {
    tagline: "Writes marketing copy for a web page from scratch (home, landing, pricing, about).",
    useWhen: "You're building or rewriting a page and need headlines and body copy.",
    example: "Write landing-page copy for GooCampus's 'MBBS in Georgia' service for Indian students.",
    expect: "Headline, sub-headline, section copy, and a call-to-action, structured top to bottom.",
    verify: "The headline names the benefit clearly; every section earns its place; one obvious next step.",
  },
  "emails": {
    tagline: "Plans and writes marketing email sequences (newsletters, nurture, announcements).",
    useWhen: "You want to email your student/lead list — a welcome series, an event push, a newsletter.",
    example: "Write a 3-email welcome sequence for students who downloaded our NEET-to-abroad guide.",
    expect: "A sequence with subject lines, timing, and the body of each email.",
    verify: "Each email has one goal and one CTA; the sequence tells a story, not the same pitch 3×.",
  },
  "image": {
    tagline: "Turns an idea into a visual brief a designer can execute (concept, layout, text on image).",
    useWhen: "You know what to say but not what the graphic should look like.",
    example: "Give me a poster brief for 'PLAB coaching batch starting soon' for Instagram.",
    expect: "A described concept: visual idea, headline text, layout, colours/mood — ready for a designer.",
    verify: "A designer could build it from the brief without asking you 10 questions.",
  },
  "pillar-content": {
    tagline: "Plans a big, comprehensive 'ultimate guide' page that ranks and gets linked to.",
    useWhen: "You want one authoritative page on a core topic (the backbone of your SEO).",
    example: "Outline a pillar guide: 'MBBS Abroad for Indian Students — the complete 2026 guide'.",
    expect: "A full outline: sections, sub-topics, questions to answer, and internal links.",
    verify: "It covers the topic more completely than the pages ranking today; logical section order.",
  },
  "sms": {
    tagline: "Writes short SMS / WhatsApp campaign messages.",
    useWhen: "You want to text leads about a deadline, event, or offer.",
    example: "Write 3 WhatsApp messages reminding leads about the NEET PG counselling webinar this Sunday.",
    expect: "A few very short messages, each with one clear action and a link placeholder.",
    verify: "Under ~160 chars, one ask each, sounds like a person — not spam.",
  },
  "social": {
    tagline: "Plans and writes social media posts and a posting angle.",
    useWhen: "You need post ideas or captions for Instagram / LinkedIn / Facebook.",
    example: "Give me 5 Instagram post ideas about common MBBS-abroad mistakes, with captions.",
    expect: "Post ideas with hooks, captions, and format suggestions (carousel/reel/static).",
    verify: "Each has a scroll-stopping first line and one takeaway; not generic 'motivational' filler.",
  },
  "video": {
    tagline: "Writes video/reel scripts and concepts.",
    useWhen: "You want a script for a reel, YouTube video, or ad.",
    example: "Write a 45-second reel script: '3 countries for affordable MBBS after NEET'.",
    expect: "A script with a hook, beats/scenes, on-screen text cues, and a CTA.",
    verify: "The first 2 seconds hook; it's shootable as written; one clear message.",
  },
  "cro": {
    tagline: "Finds why a page isn't converting and how to fix it (conversion rate optimization).",
    useWhen: "A page gets visitors but few enquiries/sign-ups.",
    example: "Audit our 'Book a free counselling call' page and suggest changes to get more bookings.",
    expect: "A prioritized list of friction points and specific fixes (copy, layout, form, trust).",
    verify: "Fixes are specific and testable, ranked by likely impact — not vague 'make it better'.",
  },
  "onboarding": {
    tagline: "Designs the first-time experience so new users/leads stick.",
    useWhen: "New leads sign up but go cold, or students don't complete a process.",
    example: "Design an onboarding flow for a student who just registered for GooCampus counselling.",
    expect: "A step-by-step flow with what to send/show at each stage and the goal of each.",
    verify: "Every step moves the person toward one 'aha' moment; nothing feels like busywork.",
  },
  "paywalls": {
    tagline: "Designs paid-content gates and the copy that makes people upgrade.",
    useWhen: "You gate premium content or a paid service and want more conversions (niche for GooCampus).",
    example: "Write the copy for a paywall on our premium 'university shortlist' tool.",
    expect: "Paywall messaging, what to show free vs paid, and the upgrade CTA.",
    verify: "The value is obvious at the gate; the free taste creates real desire for more.",
  },
  "popups": {
    tagline: "Designs website popups (email capture, offers) that don't annoy.",
    useWhen: "You want to capture leads from website visitors before they leave.",
    example: "Write an exit-intent popup offering our free 'MBBS abroad cost calculator'.",
    expect: "Popup headline, body, CTA, trigger timing, and targeting advice.",
    verify: "The offer is worth an email address; timing feels helpful, not intrusive.",
  },
  "signup": {
    tagline: "Optimizes the sign-up / registration flow to reduce drop-off.",
    useWhen: "People start registering but don't finish.",
    example: "How do we simplify the GooCampus counselling registration form to get more completions?",
    expect: "Field-by-field advice, what to cut, and flow changes to reduce friction.",
    verify: "Fewer fields, clearer value at each step; only truly-needed info is asked upfront.",
  },
  "churn-prevention": {
    tagline: "Finds why people drop off and how to keep them engaged.",
    useWhen: "Leads or students go quiet and you want to win them back / keep them.",
    example: "How do we keep MBBS-abroad leads engaged during the long 3–6 month decision period?",
    expect: "Reasons for drop-off and a retention plan (touchpoints, content, offers).",
    verify: "It targets real reasons students go cold; tactics are doable with your team.",
  },
  "co-marketing": {
    tagline: "Plans joint campaigns with a partner so both audiences grow.",
    useWhen: "You want to team up with a coaching centre, edu-brand, or hospital.",
    example: "Propose a co-marketing campaign between GooCampus and a NEET coaching institute.",
    expect: "Partnership angle, what each side gives/gets, campaign ideas, and an outreach pitch.",
    verify: "It's a fair win-win; both audiences genuinely benefit, not just us.",
  },
  "community-marketing": {
    tagline: "Builds and grows an engaged community (group, forum, cohort).",
    useWhen: "You want an active WhatsApp/Telegram/community of students, not just followers.",
    example: "Plan a WhatsApp community for aspirants preparing for MBBS abroad — structure and content.",
    expect: "Community structure, engagement rituals, content cadence, and moderation tips.",
    verify: "It gives members a reason to show up repeatedly; value flows both ways.",
  },
  "free-tools": {
    tagline: "Ideas for free tools/calculators that attract leads.",
    useWhen: "You want a magnet that pulls students in via Google and sharing.",
    example: "Suggest free tools GooCampus could build for MBBS-abroad aspirants.",
    expect: "Tool ideas with the problem each solves and how it captures leads.",
    verify: "Each tool solves a real, searched-for problem and naturally leads to your service.",
  },
  "influencer-marketing": {
    tagline: "Plans influencer / creator collaborations.",
    useWhen: "You want doctors, students, or edu-influencers to promote GooCampus.",
    example: "Plan an influencer campaign with IMG doctors on Instagram about studying medicine abroad.",
    expect: "Who to target, the collaboration format, the brief, and how to measure it.",
    verify: "The creators actually reach your students; the ask is authentic to their audience.",
  },
  "lead-magnets": {
    tagline: "Designs free downloads (guides, checklists) that capture leads.",
    useWhen: "You want emails/numbers in exchange for something genuinely useful.",
    example: "Design a lead magnet for students deciding between NEET repeat and MBBS abroad.",
    expect: "The magnet concept, outline, the landing copy, and the follow-up.",
    verify: "It's something a student would happily trade their contact for; ties to your service.",
  },
  "referrals": {
    tagline: "Designs a referral program so students bring students.",
    useWhen: "You want word-of-mouth growth from happy students/parents.",
    example: "Design a referral program where current GooCampus students refer juniors.",
    expect: "The incentive, the mechanics, the messaging, and how to track it.",
    verify: "The reward motivates without feeling cheap; the ask is easy to make and share.",
  },
  "ab-testing": {
    tagline: "Designs proper experiments to test what works.",
    useWhen: "You're guessing between two options (headline, price, creative) and want to know.",
    example: "Design an A/B test for two versions of our 'free counselling' landing headline.",
    expect: "The hypothesis, what to change, what to measure, and how long to run it.",
    verify: "Only one thing changes per test; the success metric is defined before you start.",
  },
  "ad-creative": {
    tagline: "Generates ad creative concepts (visual + copy angles).",
    useWhen: "You need fresh ideas for Meta/Google ads.",
    example: "Give me 5 ad creative concepts for GooCampus MBBS-abroad counselling for Meta.",
    expect: "Distinct concepts, each with a visual idea, hook, and primary text.",
    verify: "The angles are genuinely different (not one idea 5×); each has a clear hook.",
  },
  "ads": {
    tagline: "Plans paid ad campaigns (targeting, structure, budget logic).",
    useWhen: "You're setting up or fixing a paid campaign strategy.",
    example: "Plan a Meta ads campaign to get MBBS-abroad counselling bookings from NEET aspirants.",
    expect: "Audiences, campaign structure, creative angles, and a budget/measurement approach.",
    verify: "Targeting matches your real buyer; the funnel from ad to booking is spelled out.",
  },
  "analytics": {
    tagline: "Sets up what to measure and how to read it.",
    useWhen: "You're unsure which numbers matter or how to track them.",
    example: "What should GooCampus track to know if our marketing is actually working?",
    expect: "The key metrics, how to track each, and what 'good' looks like.",
    verify: "The metrics tie to revenue/leads, not vanity likes; each is actually trackable.",
  },
  "attribution": {
    tagline: "Works out which channels actually drive your leads/sales.",
    useWhen: "You spend on many channels and don't know what's really working.",
    example: "How do we tell whether our leads come from Instagram, Google, or referrals?",
    expect: "An attribution approach fit to your size, plus what to set up to see it.",
    verify: "The method is practical for a small team; it credits channels fairly.",
  },
  "competitor-profiling": {
    tagline: "Builds a deep profile of one specific competitor.",
    useWhen: "You want to understand a rival edu-consultancy in depth.",
    example: "Profile the marketing and positioning of [competitor name] in MBBS-abroad consulting.",
    expect: "Their positioning, channels, offers, strengths/weaknesses, and gaps you can exploit.",
    verify: "It cites real, current sources; findings are specific, not guesses.",
  },
  "competitors": {
    tagline: "Maps the competitive landscape (who's out there, how you compare).",
    useWhen: "You want the big picture of who you're up against.",
    example: "Who are GooCampus's main competitors for MBBS abroad, and how do we differ?",
    expect: "A landscape of players, how they position, and where GooCampus can stand out.",
    verify: "Names are real and current; the 'how we differ' is honest and usable.",
  },
  "directory-submissions": {
    tagline: "Finds directories/listings to get GooCampus listed in (for reach + SEO).",
    useWhen: "You want more places online that link to and list you.",
    example: "List education/study-abroad directories where GooCampus should be listed.",
    expect: "A list of directories with why each matters and how to submit.",
    verify: "The directories are real and relevant to Indian students, not spammy.",
  },
  "launch": {
    tagline: "Plans the launch of a new service, event, or campaign.",
    useWhen: "You have something new to announce and want a real launch, not a quiet post.",
    example: "Plan the launch of GooCampus's new 'PLAB mentorship' program.",
    expect: "A phased launch plan: pre-launch, launch day, follow-up — channels and messages.",
    verify: "It builds anticipation then converts; every phase has a clear job.",
  },
  "offers": {
    tagline: "Designs compelling offers/packages people say yes to.",
    useWhen: "Your service is good but the offer isn't landing.",
    example: "Design an irresistible offer for GooCampus's counselling + application package.",
    expect: "The offer structure, what's included, framing, and urgency/guarantee ideas.",
    verify: "The value clearly outweighs the price; the offer is easy to understand fast.",
  },
  "pricing": {
    tagline: "Helps set and present pricing.",
    useWhen: "You're deciding what to charge or how to show prices.",
    example: "How should GooCampus price and present its MBBS-abroad application service?",
    expect: "Pricing structure options, tiers, and how to present them persuasively.",
    verify: "Tiers map to real segments; the recommended option is easy to pick.",
  },
  "prospecting": {
    tagline: "Finds and qualifies potential leads/partners.",
    useWhen: "You need a system to find the right people to reach out to.",
    example: "How do we find and qualify B2B partners (schools, coaches) for GooCampus referrals?",
    expect: "Where to find them, how to qualify, and an outreach starting point.",
    verify: "The sourcing is realistic for your team; qualification filters out time-wasters.",
  },
  "public-relations": {
    tagline: "Plans PR / media outreach to get GooCampus covered.",
    useWhen: "You want press, features, or credibility from media mentions.",
    example: "Plan a PR angle to get GooCampus featured in education media around NEET results season.",
    expect: "Story angles, target outlets/journalists, and a pitch.",
    verify: "The angle is newsworthy (not an ad); outlets actually cover this beat.",
  },
  "revops": {
    tagline: "Aligns your sales + marketing operations and process.",
    useWhen: "Leads leak between marketing and the counselling/sales team.",
    example: "How should GooCampus handle a lead from first enquiry to enrolled, without leaks?",
    expect: "A process/handoff design, stages, and what to track at each.",
    verify: "Every lead has a clear next owner and step; nothing falls through gaps.",
  },
  "sales-enablement": {
    tagline: "Creates materials/scripts that help your team close.",
    useWhen: "Your counsellors need better talking points, decks, or objection answers.",
    example: "Write objection-handling scripts for parents worried about MBBS abroad safety and fees.",
    expect: "Scripts, talking points, and materials your counsellors can use in calls.",
    verify: "It answers the objections you actually hear; sounds natural on a call.",
  },
  "ai-seo": {
    tagline: "Gets GooCampus cited when students ask AI (ChatGPT, Perplexity, Google AI Overviews).",
    useWhen: "You want to show up in AI answers, not just Google's blue links (a.k.a. GEO/AEO).",
    example: "How do we get GooCampus cited when students ask ChatGPT 'best country for MBBS after NEET'?",
    expect: "The AI queries to target, why AI cites some sites, and a checklist (content, schema, llms.txt, authority).",
    verify: "Open the cited sources — real and recent? Then ask ChatGPT/Perplexity the query and see who's cited today.",
  },
  "aso": {
    tagline: "Optimizes an app's store listing to get more downloads.",
    useWhen: "Only relevant if GooCampus has a mobile app to promote.",
    example: "Optimize the App Store listing for a GooCampus student app.",
    expect: "Title, keywords, description, and screenshot guidance for the store.",
    verify: "Keywords match what students search in the store; the value is clear in 1 line.",
  },
  "content-strategy": {
    tagline: "Decides what content to make and in what order — your content plan.",
    useWhen: "You don't know what to post/write next (start here before writing).",
    example: "Build a 3-month content plan for GooCampus targeting NEET aspirants considering abroad.",
    expect: "Themes, specific topics, formats, and a schedule tied to your audience's journey.",
    verify: "Topics map to what students actually search/ask; it's realistic for your team to produce.",
  },
  "programmatic-seo": {
    tagline: "Plans many similar pages generated from data (scaled SEO).",
    useWhen: "You could make one page per country/university/exam from a data set.",
    example: "Plan programmatic pages: 'MBBS in [country] for Indian students' across 15 countries.",
    expect: "A page template, the data needed, URL pattern, and how to avoid thin/duplicate pages.",
    verify: "Each generated page is genuinely useful on its own, not empty filler.",
  },
  "schema": {
    tagline: "Adds structured data (code) so Google shows rich results.",
    useWhen: "You want FAQs, ratings, courses etc. to show as rich snippets — technical.",
    example: "Generate FAQ schema markup for our 'MBBS in Russia' page.",
    expect: "Ready-to-paste JSON-LD structured-data code plus where to put it.",
    verify: "Paste it into Google's Rich Results Test — it should validate with no errors.",
  },
  "seo-audit": {
    tagline: "Checks a page/site for SEO problems and fixes (technical + on-page).",
    useWhen: "You want to know why a page isn't ranking and what to fix.",
    example: "Audit our 'MBBS in Georgia' page for SEO issues and fixes.",
    expect: "A prioritized list of issues (title, headings, content, speed, links) with fixes.",
    verify: "Fixes are specific and doable; ranked by impact — pair it with the SEO tab's rank data.",
  },
  "site-architecture": {
    tagline: "Plans how your site's pages and URLs should be organised.",
    useWhen: "Your site is growing messy or you're planning many new pages.",
    example: "Design the page/URL structure for GooCampus covering countries, exams, and services.",
    expect: "A site map: main sections, sub-pages, URL patterns, and internal-link logic.",
    verify: "A new visitor could find anything in 2–3 clicks; related pages link to each other.",
  },
  "customer-research": {
    tagline: "Helps you understand your audience deeply (their real needs/words).",
    useWhen: "You want to truly get what students/parents worry about and want.",
    example: "What are the real fears and decision factors for parents choosing MBBS abroad?",
    expect: "Audience insights: motivations, fears, objections, and the words they use.",
    verify: "It matches what you hear on real calls; specific, not generic personas.",
  },
  "marketing-council": {
    tagline: "Gives you several expert viewpoints on a decision, like a panel.",
    useWhen: "You have a big decision and want it pressure-tested from many angles.",
    example: "Should GooCampus focus budget on Instagram or SEO this quarter? Give me the panel's views.",
    expect: "Multiple expert perspectives (pro/con) and a synthesized recommendation.",
    verify: "It surfaces trade-offs you hadn't considered; the final call is reasoned, not hand-wavy.",
  },
  "marketing-ideas": {
    tagline: "Brainstorms a batch of growth/marketing ideas fast.",
    useWhen: "You're stuck and want a spread of options to pick from.",
    example: "Give me 15 low-budget marketing ideas for GooCampus to get MBBS-abroad leads.",
    expect: "A varied list of ideas, each with the gist of how to do it.",
    verify: "Ideas fit your budget/team; at least a few are genuinely new to you.",
  },
  "marketing-loops": {
    tagline: "Designs self-reinforcing growth loops (where output feeds more input).",
    useWhen: "You want growth that compounds, not one-off campaigns.",
    example: "Design a growth loop where GooCampus students bring in new aspirants automatically.",
    expect: "A described loop: the trigger, the action, and how it feeds itself, plus metrics.",
    verify: "Each cycle plausibly creates more than one new cycle; the loop actually closes.",
  },
  "marketing-plan": {
    tagline: "Builds an overall marketing strategy/plan.",
    useWhen: "You want the big-picture plan, not a single tactic (great starting point).",
    example: "Build a 6-month marketing plan for GooCampus to grow MBBS-abroad enrolments.",
    expect: "Goals, audiences, channels, key campaigns, and a rough timeline/priorities.",
    verify: "It's focused (a few bets, not everything); goals are concrete and time-bound.",
  },
  "marketing-psychology": {
    tagline: "Applies persuasion principles (why people say yes) to your marketing.",
    useWhen: "You want any piece to be more convincing (pairs with copywriting/offers).",
    example: "Which psychology principles should GooCampus use to reassure anxious MBBS-abroad parents?",
    expect: "Relevant principles (trust, social proof, loss aversion…) applied to your case.",
    verify: "The tactics are honest (real proof, real urgency) — never manipulative or invented.",
  },
  "product-marketing": {
    tagline: "Nails positioning and messaging for a service/product.",
    useWhen: "You struggle to explain what makes a GooCampus service different/better.",
    example: "Write the positioning and messaging for GooCampus's end-to-end MBBS-abroad service.",
    expect: "A positioning statement, key messages, and the differentiators to lead with.",
    verify: "A stranger understands what it is and why it's better in one read; it's true to you.",
  },
};
